version: "3"
services:
  data_extraction:
    build:
      context: .
    container_name: data-extractor-mqtt
    user: "1001"
    working_dir: /app
    volumes:
      - ./logs:/app/logs
      - /srv/data/mqtt_network/raw:/app/output
      - /srv/data/mqtt_network/processed:/app/processed_output
      - ./config:/app/config
      - /etc/localtime:/etc/localtime:ro # sync timezone with host machine
    command: ["python", "main.py"]
    networks:
      - mqtt5-network
      - metrics-network

networks:
  mqtt5-network:
    external: true

  metrics-network:
    external: true