secrets_filepath = ".env"

[mqtt.broker]
# hostname = "emqx-broker"  # For running as docker container
hostname = "gfyvrdatadash"
port = 1_883

[mqtt.node_network]
topic_structure = "machine/module/measurement/field*"
enable_prometheus_server = false
prometheus_port = 8_000

[data_extraction]
name = "data_extraction"
node_id = "data_extraction"
id_structure = "measurement/field*"
max_buffer_length = 100
max_buffer_time = 10
resample_time = 1
raw_ouput_filename = "topics"
processed_output_filename = "prototype-zero"
subscriptions = [
    "prototype-zero/#"
]