secrets_filepath = ".env"

[mqtt.broker]
hostname = "emqx-broker"  # For running as docker container
# hostname = "gfyvrdatadash"
port = 1_883

[mqtt.node_network]
topic_structure = "machine/permission/category/module/measurement/field*"
# topic_structure = "machine/module/measurement/field*"
enable_prometheus_server = true
prometheus_port = 8_000

[data_extraction]
name = "data_extraction"
node_id = "data_extraction"
max_buffer_length = 100
max_buffer_time = 10
subscriptions = [
    "prototype-zero/#",
]
id_structure = "category/measurement/field*"
# id_structure = "measurement/field*"
resample_time = 1
nan_limit = 4
ouput_filename = "topics"
output_directory = "output"
processed_output_filename = "prototype-zero"
processed_output_directory = "processed_output"

